# This is a basic workflow to help you get started with Actions

name: CI

# Triggers the workflow at 4:05 am on the 7th day on every month
on:
  schedule:
    - cron: '5 4 7 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: update file and push to remote
        run: |
          make
          curl -sL https://easylist-downloads.adblockplus.org/easylistchina.txt | ./hostsblock - > easylist.txt

          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add easylist.txt
          git commit -m "Update easylist.txt"
          git push
